/* ===== shop.js — فلترة + سلة محلية ===== */
(()=>{const KEY='cart_items_v1',load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}},save=a=>localStorage.setItem(KEY,JSON.stringify(a)),money=n=>((+n||0).toFixed(2))+'$';
function ensureFilterUI(c){if(!c||document.getElementById('filter-box')||!c.parentNode)return;const f=document.createElement('fieldset');f.id='filter-box';f.innerHTML=`<legend>تصفية</legend><label><input type="radio" name="ftype" id="f-all" checked> الكل</label><label><input type="radio" name="ftype" id="f-honey"> عسل</label><label><input type="radio" name="ftype" id="f-coffee"> قهوة</label>`;c.parentNode.insertBefore(f,c)}
function pickPrice(t){const m=t.match(/(\d+(?:\.\d+)?)\s*(?:\$|ر\.?\s*س|sar|ريال)?/i);return m?m[1]:null}
function categorize(c){const cards=c?c.querySelectorAll('.card, article, .product'):[];let i=0;cards.forEach(k=>{i++;const txt=(k.textContent||'').toLowerCase();let t='other';if(txt.includes('عسل')||txt.includes('honey'))t='honey';if(txt.includes('قهوة')||txt.includes('بن')||txt.includes('coffee'))t='coffee';if(!k.dataset.id)k.dataset.id='p'+i; if(!k.dataset.name){const h=k.querySelector('h3,h2,.title');k.dataset.name=h?(h.textContent||('منتج '+i)):('منتج '+i)} if(!k.dataset.price){k.dataset.price=pickPrice(txt)||'10'} k.dataset.type=k.dataset.type||t; if(!k.querySelector('.add-to-cart')){const b=document.createElement('button');b.className='btn add-to-cart';b.type='button';b.textContent='أضف للسلة';k.appendChild(b)}})}
function filters(c){const items=c?Array.from(c.querySelectorAll('[data-type]')):[];const show=t=>items.forEach(it=>{it.style.display=(!t||it.dataset.type===t)?'':'none'});const fh=document.getElementById('f-honey'),fc=document.getElementById('f-coffee'),fa=document.getElementById('f-all');fa&&fa.addEventListener('change',()=>show(null));fh&&fh.addEventListener('change',()=>show('honey'));fc&&fc.addEventListener('change',()=>show('coffee'));show(null)}
function cartButtons(root){let lock=false;root.addEventListener('click',e=>{const b=e.target.closest('.add-to-cart');if(!b||lock)return;lock=true;setTimeout(()=>lock=false,250);const card=b.closest('[data-id]')||b.closest('.card,article,.product');if(!card)return;const id=card.dataset.id,name=card.dataset.name||'منتج',price=parseFloat(card.dataset.price||'10');const cart=load();const f=cart.find(i=>i.id===id);f?f.qty++:cart.push({id,name,price,qty:1});save(cart);try{b.textContent='✓ تمت الإضافة';setTimeout(()=>b.textContent='أضف للسلة',1200)}catch{};renderCart()})}
function renderCart(){const root=document.getElementById('cart-root'),listEl=document.getElementById('cart-list');if(!root&&!listEl)return;if(root&&!listEl){root.innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>المنتج</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th><th></th></tr></thead><tbody id="cart-list"></tbody><tfoot><tr><td colspan="3">الإجمالي</td><td id="cart-total">0$</td><td></td></tr></tfoot></table></div>`}
const list=document.getElementById('cart-list'),total=document.getElementById('cart-total');if(!list||!total)return;const cart=load();let sum=0;list.innerHTML=cart.map(i=>{const line=i.price*i.qty;sum+=line;return `<tr><td>${i.name}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(line)}</td><td><button class="btn remove" data-id="${i.id}">حذف</button></td></tr>`}).join('')||`<tr><td colspan="5">السلة فارغة</td></tr>`;total.textContent=money(sum);list.onclick=e=>{const r=e.target.closest('.remove');if(!r)return;const id=r.getAttribute('data-id');save(load().filter(i=>i.id!==id));renderCart()}}
document.addEventListener('DOMContentLoaded',()=>{const pc=document.querySelector('.products,.product-grid,.items');ensureFilterUI(pc);categorize(pc);filters(pc);cartButtons(document);renderCart()})})();
